epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: '0.0.0.0:40772'
  mounts:
    /miraview:
      path: /var/www/miraview
      index: index.html

channels:
  - name: NHKEテレ大阪
    type: GR
    channel: '13'
    isDisabled: false
  - name: 読売テレビ
    type: GR
    channel: '14'
    isDisabled: false
  - name: ABCテレビ
    type: GR
    channel: '15'
    isDisabled: false
  - name: MBS毎日放送
    type: GR
    channel: '16'
    isDisabled: false
  - name: 関西テレビ
    type: GR
    channel: '17'
    isDisabled: false
  - name: テレビ大阪
    type: GR
    channel: '18'
    isDisabled: false
  - name: NHK総合・大阪
    type: GR
    channel: '24'
    isDisabled: false
  - name: サンテレビ
    type: GR
    channel: '26'
    isDisabled: false

tuners:
  - name: adapter0
    types:
      - GR
    dvbDevicePath: /dev/dvb/adapter0/dvr0
    decoder: arib-b25-stream-test
    command: >-
      dvbv5-zap -a 0 -c ./config/dvbconf-for-isdb/conf/dvbv5_channels_isdbt.conf
      -r -P <channel>

filters:
  decode-filter:
    command: >-
      recisdb decode --input - -
