services:
  mirakc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mirakc-epg:/var/lib/mirakc/epg/
      - ./config.yml:/etc/mirakc/config.yml:ro

volumes:
  mirakc-epg:
